import "./globals.css";
import Navbar from "./components/navBar";
import "@fortawesome/fontawesome-svg-core/styles.css";
import { config } from "@fortawesome/fontawesome-svg-core";
import { Poppins } from '@next/font/google';
config.autoAddCss = false;

const poppins = Poppins({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700', '800', '900'],
})

export const metadata = {
  title: "Pawfect Match",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
