import localFont from "next/font/local";
import "./globals.css";
import Navbar from "./components/navBar";


export const metadata = {
  title: "Pawfect Match",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <main>{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
